import os

EMAIL_HOST = os.environ["MAILGUN_SMTP_SERVER"]
EMAIL_HOST_USER = os.environ["MAILGUN_SMTP_LOGIN"]
EMAIL_HOST_PASSWORD = os.environ["MAILGUN_SMTP_PASSWORD"]
EMAIL_PORT = os.environ["MAILGUN_SMTP_PORT"]
