# Build Stage
FROM python:3.9.15-alpine AS builder

RUN pip install --upgrade pip

COPY /requirements /requirements

RUN pip install -r /requirements/dev.txt



# Run Stage
FROM python:3.9.15-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add bash

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

COPY . /app
