version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

  smtp4dev:
    image: rnwood/smtp4dev:3.2.0-ci20221023104
    ports:
      - 25:25
      - 2525:80
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: on-failure

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: on-failure

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A config flower
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555
    restart: always

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./wait-for-it.sh db:5432 -- python manage.py test
    depends_on:
      - db
      - redis
    tty: true
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: on-failure

volumes:
  postgres-data:
  redis-data:
