version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

  smtp4dev:
    image: rnwood/smtp4dev:3.2.0-ci20221023104
    ports:
      - 25:25
      - 2525:80
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: on-failure

volumes:
  postgres-data:
  redis-data:
