version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app

volumes:
  postgres-data:
